name: scar-env
channels:
  - plotly
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0=hcec6c5f_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=hcec6c5f_0
  - brotli-bin=1.0.9=hca72f7f_7
  - brotli-python=1.0.9=py310he9d5cce_7
  - brunsli=0.1=h23ab428_0
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2024.2.2=h8857fd0_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cfitsio=3.470=hbd21bf8_7
  - charls=2.2.0=h23ab428_0
  - charset-normalizer=3.3.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dask-core=2023.6.0=py310hecd8cb5_0
  - datashader=0.16.0=pyhd8ed1ab_0
  - dav1d=1.2.1=h6c40b1e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - giflib=5.2.1=h6c40b1e_3
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - holoviews=1.18.0=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=ha357a0b_43547
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.22.2=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9e=h6c40b1e_1
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310h2ec42d9_0
  - jxrlib=1.1=haf1e3a3_2
  - krb5=1.20.1=h428f121_1
  - lazy_loader=0.3=py310hecd8cb5_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libaec=1.0.4=hb1e8313_1
  - libavif=0.11.1=h6c40b1e_0
  - libbrotlicommon=1.0.9=hca72f7f_7
  - libbrotlidec=1.0.9=hca72f7f_7
  - libbrotlienc=1.0.9=hca72f7f_7
  - libcurl=8.4.0=hf20ceda_0
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.17=hb664fd8_1
  - libedit=3.1.20221030=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libidn2=2.3.4=h6c40b1e_0
  - libllvm14=14.0.6=h91fad77_3
  - libnghttp2=1.57.0=h9beae6a_0
  - libopenblas=0.3.21=h54e7dc3_0
  - libpng=1.6.39=h6c40b1e_0
  - libprotobuf=3.20.3=hfff2838_0
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.10.0=h04015c4_2
  - libtiff=4.5.1=hcec6c5f_0
  - libunistring=0.9.10=h9ed2024_0
  - libwebp=1.3.2=hf6ce154_0
  - libwebp-base=1.3.2=h6c40b1e_0
  - libzopfli=1.0.3=hb1e8313_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - lz4-c=1.9.4=hcec6c5f_0
  - matplotlib-base=3.7.2=py310hee32256_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h8e150cf_43559
  - munkres=1.1.4=py_0
  - ncurses=6.4=hcec6c5f_0
  - nomkl=3.0=0
  - numpy-base=1.24.3=py310h992e150_0
  - openjpeg=2.4.0=h66ea3da_0
  - openssl=3.2.1=hd75f5a5_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - plotly=5.17.0=py_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.13=h5ee71fb_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pyviz_comms=2.3.0=py310hecd8cb5_0
  - readline=8.2=hca72f7f_0
  - requests=2.31.0=pyhd8ed1ab_0
  - sentry-sdk=1.32.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.9=he9d5cce_0
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h5d9f67b_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - wandb=0.15.12=pyhd8ed1ab_0
  - xz=5.4.2=h6c40b1e_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.5=h93d8f39_0
  - zfp=1.0.0=hcec6c5f_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.5=hc035e20_0
  - pip:
    - absl-py==2.0.0
    - adjusttext==0.8
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - anndata==0.10.3
    - annotated-types==0.6.0
    - anyio==3.7.1
    - array-api-compat==1.4
    - arrow==1.3.0
    - astunparse==1.6.3
    - async-timeout==4.0.3
    - attrs==23.1.0
    - backoff==2.2.1
    - beautifulsoup4==4.12.2
    - blessed==1.20.0
    - bokeh==3.3.0
    - boto3==1.28.76
    - botocore==1.31.76
    - bottleneck==1.3.5
    - brotli==1.0.9
    - chex==0.1.7
    - cloudpickle==2.2.1
    - colorcet==3.0.1
    - colourmap==1.1.16
    - contextlib2==21.6.0
    - contourpy==1.0.5
    - croniter==1.4.1
    - cytoolz==0.12.0
    - dask==2023.6.0
    - datazets==0.1.9
    - dateutils==0.6.12
    - debugpy==1.8.1
    - deepdiff==6.6.1
    - dm-tree==0.1.8
    - docrep==0.3.2
    - et-xmlfile==1.1.0
    - etils==1.5.2
    - exceptiongroup==1.1.3
    - fastapi==0.104.1
    - filelock==3.13.1
    - flatbuffers==24.12.23
    - flax==0.7.5
    - frozenlist==1.4.0
    - fsspec==2023.9.2
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.68.1
    - h11==0.14.0
    - h5py==3.10.0
    - imageio==2.31.4
    - importlib-metadata==6.0.0
    - importlib-resources==6.1.0
    - inquirer==3.1.3
    - itsdangerous==2.1.2
    - jax==0.4.19
    - jaxlib==0.4.19
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.3.2
    - jupyter-core==5.7.2
    - kaleido==0.2.1
    - keras==3.7.0
    - kiwisolver==1.4.4
    - lazy-loader==0.3
    - libclang==18.1.1
    - lightning==2.0.9.post0
    - lightning-cloud==0.5.46
    - lightning-utilities==0.9.0
    - linkify-it-py==2.0.0
    - llvmlite==0.41.1
    - locket==1.0.0
    - markdown==3.4.1
    - markdown-it-py==2.2.0
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.2
    - ml-collections==0.1.1
    - ml-dtypes==0.3.1
    - mpmath==1.3.0
    - msgpack==1.0.7
    - mudata==0.2.3
    - multidict==6.0.4
    - multipledispatch==0.6.0
    - namex==0.0.8
    - natsort==8.4.0
    - nest-asyncio==1.5.8
    - networkx==3.2.1
    - numba==0.58.1
    - numexpr==2.8.7
    - numpy==1.24.3
    - numpyro==0.13.2
    - opencv-python==4.9.0.80
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - optax==0.1.7
    - optree==0.13.1
    - orbax-checkpoint==0.4.1
    - ordered-set==4.1.0
    - packaging==23.1
    - pandas==2.1.1
    - pandas-flavor==0.6.0
    - panel==1.3.0
    - param==2.0.0
    - partd==1.4.1
    - patsy==0.5.3
    - pca==2.0.5
    - pillow==10.0.1
    - pip==24.3.1
    - protobuf==3.20.3
    - psutil==5.9.0
    - pyct==0.5.0
    - pydantic==2.1.1
    - pydantic-core==2.4.0
    - pygments==2.16.1
    - pyjanitor==0.27.0
    - pyjwt==2.8.0
    - pynndescent==0.5.10
    - pyparsing==3.0.9
    - pyro-api==0.1.2
    - pyro-ppl==1.8.6
    - python-editor==1.0.4
    - python-multipart==0.0.6
    - pytorch-lightning==2.1.0
    - pytz==2023.3.post1
    - pyviz-comms==2.3.0
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - readchar==4.0.5
    - rich==13.6.0
    - s3transfer==0.7.0
    - scanpy==1.9.5
    - scatterd==1.3.7
    - scikit-image==0.20.0
    - scikit-learn==1.3.2
    - scipy==1.11.3
    - scperturb==0.1.0
    - scvi-tools==1.0.4
    - seaborn==0.13.0
    - session-info==1.0.0
    - setproctitle==1.2.2
    - setuptools==68.0.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - sparse==0.14.0
    - starlette==0.27.0
    - starsessions==1.3.0
    - statsmodels==0.14.0
    - stdlib-list==0.9.0
    - sympy==1.12
    - tbb==2021.10.0
    - tenacity==8.2.2
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - tensorflow==2.16.2
    - tensorflow-io-gcs-filesystem==0.37.1
    - tensorstore==0.1.46
    - termcolor==2.5.0
    - threadpoolctl==3.2.0
    - tifffile==2023.4.12
    - toolz==0.12.0
    - torch==2.1.0
    - torchmetrics==1.2.0
    - tornado==6.3.3
    - tqdm==4.65.0
    - traitlets==5.13.0
    - types-python-dateutil==2.8.19.14
    - uc-micro-py==1.0.1
    - umap-learn==0.5.4
    - uvicorn==0.23.2
    - wcwidth==0.2.9
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - websockets==12.0
    - werkzeug==3.1.3
    - wheel==0.41.2
    - wrapt==1.17.0
    - xarray==2023.6.0
    - xyzservices==2022.9.0
    - yarl==1.9.2
    - zipp==3.11.0
