train: True
test: False
qq: False
id: species-testrabbit-ARFalse-oodTrue-varconFalse-per1.0-lr5e-05-wd5e-05-bs2048-ldim64-epoch1000-seed100
model: Naive
AR: False
latent_dim: 64
num_epoch: 1000
optimizer: adam
batch_size: 2048
lr: 5e-05
weight_decay: 5e-05
w_update: max_w
bins: 100
alpha: 0.0001
data: species
train_data: ['mouse', 'pig', 'rat']
test_data: ['rabbit']
ood: True
variable_con: False
con_percent: 1.0
in_dist_group: 
seed: 100
ckpt: /home/v-mahughes/sc-uncertainty/saved_models/species/seed100/
adata_label_cell: species
adata_label_per: LPS6
adata_label_unper: unst
checkpoint: 500
gpu: True
_wandb: {}
best_epoch: 246
