train: True
test: False
qq: False
id: lps-hpoly-testTA.Early-ARFalse-oodTrue-varconFalse-per1.0-lr5e-05-wd5e-05-bs2048-ldim64-epoch2000-seed100
model: Naive
AR: False
latent_dim: 64
num_epoch: 2000
optimizer: adam
batch_size: 2048
lr: 5e-05
weight_decay: 5e-05
w_update: max_w
bins: 100
alpha: 0.0001
data: lps-hpoly
train_data: ['Endocrine', 'Enterocyte', 'Enterocyte.Progenitor', 'Goblet', 'Stem', 'TA', 'Tuft']
test_data: ['TA.Early']
ood: True
variable_con: False
con_percent: 1.0
in_dist_group: 
seed: 100
ckpt: /home/v-mahughes/sc-uncertainty/saved_models/lps-hpoly/seed100/
adata_label_cell: cell_label
adata_label_per: Hpoly.Day10
adata_label_unper: Control
checkpoint: 500
gpu: True
_wandb: {}
best_epoch: 1993
