train: True
predict: False
test: False
qq: False
update_old_model_name: False
id: pbmc-testB-ARTrue-oodTrue-varconTrue-per0.8-lr5e-05-wd5e-05-bs2048-ldim64-epoch1800-seed300
test_id: 
model: AR,Naive
AR: True
latent_dim: 64
num_epoch: 1800
optimizer: adam
batch_size: 2048
lr: 5e-05
weight_decay: 5e-05
w_update: max_w
bins: 100
alpha: 0.0001
data: pbmc
train_data: ['CD4T', 'NK', 'CD14+Mono', 'Dendritic', 'CD8T', 'FCGR3A+Mono']
test_data: ['B']
ood: True
variable_con: True
con_percent: 0.8
in_dist_group: 
seed: 300
ckpt: /home/v-akthoutam/sc-uncertainty/saved_models/pbmc/seed300/
adata_label_cell: cell_type
adata_label_per: stimulated
adata_label_unper: control
checkpoint: 500
gpu: True
_wandb: {}
best_epoch: 1796
